### ISSUE TITLE
HaxeUI - build macro not being run

### ISSUE THREAD

**Issue by bendmorris** [HaxeFoundation/haxe#4607]
This is happening on the current development branch of Haxe. Thus far I haven't been able to reproduce this with a simpler test case.

HaxeUI has a DisplayObject class with several build macros:

```
@:build(haxe.ui.toolkit.core.Macros.addEvents([
    "init", "resize", "ready",
    "click", "mouseDown", "mouseUp", "mouseOver", "mouseOut", "mouseMove", "doubleClick", "rollOver", "rollOut", "change", "scroll",
    "added", "addedToStage", "removed", "removedFromStage", "activate", "deactivate",
    "glyphClick",
    "menuSelect", "menuOpen"
]))
@:build(haxe.ui.toolkit.core.Macros.addClonable())
@:autoBuild(haxe.ui.toolkit.core.Macros.addClonable())
@:event("UIEvent.INIT", "Dispatched when the display object has been initialized")
@:event("UIEvent.READY", "Dispatched when the display object is ready")
@:event("UIEvent.ADDED_TO_STAGE", "Dispatched when a display object is added to the on stage display list")
@:event("UIEvent.REMOVED_FROM_STAGE", "Dispatched when a display object is about to be removed from the display list")
@:event("UIEvent.RESIZE", "Dispatched when the display object has been resized")
class DisplayObject implements IEventDispatcher implements IDisplayObject implements IDrawable implements IClonable<DisplayObject> {
```

The first, addEvents, adds fields with the corresponding names to the class (onInit, onResize, onReady...) HaxeUI components all extend some class which down the line extends DisplayObject, so they should all have these fields in common.

In all of my test projects using HaxeUI, this build macro is no longer being run after upgrading from 3.2.0 to development, resulting in compilation errors:

```
src-client/chomper/ui/LoginPopup.hx:44: characters 3-16 : haxe.ui.toolkit.core.Root has no field onResize
src-client/chomper/ui/LoginPopup.hx:44: characters 19-30 : haxe.ui.toolkit.containers.Absolute has no field onReady
src-client/chomper/ui/LoginPopup.hx:105: characters 3-19 : haxe.ui.toolkit.controls.Button has no field onClick
src-client/chomper/ui/GameOverPopup.hx:44: characters 3-16 : haxe.ui.toolkit.core.Root has no field onResize
src-client/chomper/ui/GameOverPopup.hx:44: characters 19-30 : haxe.ui.toolkit.containers.Absolute has no field onReady
src-client/chomper/ui/GameOverPopup.hx:84: characters 3-19 : haxe.ui.toolkit.controls.Button has no field onClick
```

**Comment by nadako** [comment]
This is probably the same as #4454

**Comment by bendmorris** [comment]
Seems likely, thanks. Closing this as a duplicate.
