### ISSUE TITLE
[cs][java] Issue with inlining and generics

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#6833]
Sorry for the amount of code, but I can't reduce it anymore.
```haxe
class Test {
	static public function main() {
		for(p in new KeyValueIterator([1 => 'hello'])) {}
	}
}

class KeyValueIterator<K,V> {
	var map:Map<K,V>;
	var keys:Iterator<K>;

	public inline function new(map:Map<K,V>) {
		this.map = map;
		this.keys = map.keys();
	}

	public inline function hasNext():Bool {
		return keys.hasNext();
	}

	public inline function next():KeyValuePair<K,V> {
		var key = keys.next();
		return new KeyValuePair<K,V>(key, map.get(key));
	}
}

class KeyValuePair<K,V> {
	public var key (default,null):K;
	public var value (default,null):Null<V>;

	public inline function new(key:K, value:Null<V>) {
		this.key = key;
		this.value = value;
	}
}
```
Building for C# with the latest dev:
```
$ haxe tests.hxml -cs bin/cs
haxelib run hxcs hxcs_build.txt --haxe-version 4000 --feature-level 1
Note: dmcs is deprecated, please use mcs instead!
/home/alex/mine/iterators/test/Test.hx(3,71): error CS0246: The type or namespace name `K' could not be found. Are you missing an assembly reference?
/home/alex/mine/iterators/test/Test.hx(3,74): error CS0246: The type or namespace name `V' could not be found. Are you missing an assembly reference?
Compilation failed: 2 error(s), 0 warnings
Compilation error
Native compilation failed
test/Test.hx:3: characters 3-52 : Warning : Type Int is being cast to the unrelated type KeyValueIterator.K
Error: Build failed
```
Generated C#:
```cs
public static void main() {
	unchecked {
		global::haxe.ds.IntMap<object> _g = new global::haxe.ds.IntMap<object>();
		_g.@set(1, "hello");
		object _g1_keys = ((global::haxe.IMap<int, object>) (_g) ).keys();
		while (global::haxe.lang.Runtime.toBool(global::haxe.lang.Runtime.callField(_g1_keys, "hasNext", 407283053, null))) {
			int key = ((int) (global::haxe.lang.Runtime.toInt(global::haxe.lang.Runtime.callField(_g1_keys, "next", 1224901875, null))) );
			((global::haxe.IMap<K, V>) (global::haxe.IMap__Statics_.__hx_cast<K, V>(((global::haxe.IMap) (((global::haxe.IMap<int, object>) (_g) )) ))) ).@get(global::haxe.lang.Runtime.genericCast<K>(((object) (key) )));
		}

	}
}
```
The same issue exists for java.

It works fine with Haxe 3.4.*, so it's a regression.

**Comment by Simn** [comment]
This is labeled as regression so it should be looked at for 4.0.

**Comment by Simn** [comment]
Well, shit... this is actually the same as #7579 which was fixed in https://github.com/HaxeFoundation/haxe/commit/c0ced01d76c1b8b1fcd8bb54e10aa0275a9f981a but just reverted in https://github.com/HaxeFoundation/haxe/commit/34cbf11ae2e7b8cdd05db4279dd4bab1f15bd75b because of #7617.
