### ISSUE TITLE
error C2227: left of '->reinterpret' must point to class/struct/union/generic type

### ISSUE THREAD

**Issue by intoxopox** [HaxeFoundation/haxe#9495]
I'm getting the following error in Haxe 4.1.0 and 4.1.1 that worked in 4.0.5:
`error C2227: left of '->reinterpret' must point to class/struct/union/generic type`
When trying the following sample:
```
class Main 
{
	static function main() {
		#if cpp
		var testString:String = "Hi there";
		var rawPointerReturnVal:cpp.RawConstPointer<cpp.Void> = cpp.StdString.ofString(testString).c_str().reinterpret().constRaw;
		#end
	}
}
```
Resulting relevant cpp:
```
void Main_obj::main(){
            	HX_STACKFRAME(&_hx_pos_e47a9afac0942eb9_9_main)
HXLINE(  11)		::String testString = HX_("Hi there",25,dc,6f,ff);
HXLINE(  12)		const void* rawPointerReturnVal = ::hx::StdString(testString).c_str()->reinterpret()->get_constRaw();
            	}
```

**Comment by hughsando** [comment]
Extern definitions that return RawPointers are generally going to be inconsistent at some point.  The correct definition should really be `function c_str():ConstStar<Char>;` and then the usage should be `var rawPointerReturnVal:cpp.ConstStar<cpp.Void> = cast cpp.StdString.ofString(testString).c_str();`

To get it to work as it did 4.0, I assume I will need to revert the auto-casting change that fixed a different bug.  So I'm not really sure how to fix this in the least breaking way.  As a workaround, you could make your own std::string extern (my.StdString) with the above fix.

Also, as it is written, the rawPointerReturnVal will point to freed memory, but I'm guessing that the code was only for example purposes.

**Comment by intoxopox** [comment]
Hi Hugh. Yeah, that was for example purposes. However, what I'm attempting is similarly a _mess_, but here's a fuller broken example that may provide some context... meant to allow host to call functions I expose, and optionally return to a buffer. You can see other things I've toyed with for rawPointerReturnVal.
```
/**
 * Calls function in invokeJson string, having shape { functionName:String, externalComCallID:Int, ?arguments:Array<ValueShape> }
 * ValueShape for arguments array has shape { type:String, value:Dynamic }
 * @param	invokeJson
 * @param	returnBuf
 * @param	returnLength
 */
public static function callFunction(invokeJson:ExternalCom.StringOrConstCharStar, returnBuf:cpp.CastCharStar, returnLength:Int):Void {
	var internalReturnBuf:cpp.RawPointer<cpp.Void> = cast returnBuf.toPointer();
	var returnVal:String = ExternalCom.callFunction(invokeJson);
	//var rawPointerReturnVal:cpp.RawConstPointer<cpp.Void> = cast cpp.RawConstPointer.addressOf(cpp.ConstCharStar.fromString(returnVal));
	//var rawPointerReturnVal:cpp.RawConstPointer<cpp.Void> = cast cpp.ConstCharStar.fromString(returnVal).toPointer();
	var rawPointerReturnVal = cpp.StdString.ofString(returnVal).c_str().reinterpret().constRaw;
	var sizeOf:Int = returnVal.length + 1;
	if (sizeOf < returnLength) {
		cpp.Stdlib.nativeMemcpy(internalReturnBuf, rawPointerReturnVal, sizeOf);
	} else {
		trace('OOPS: Expected return size: $sizeOf to be no larger than $returnLength');
	}
}
```

**Comment by hughsando** [comment]
Yes, it still looks like the temp string might get collected before you have the chance to memcpy it away.  I would suggest storing it in a local, like:
```haxe
var tmpString = cpp.StdString.ofString(returnVal);
var rawPointerReturnVal = tmpString.c_str().reinterpret().constRaw;
```
Another way of dealing with this is to jump out to some local c++ code via an inline extern.  This also allows for more complex interactions if requires.  If the code gets too big for inline meta, you can use "include" meta to put the code in a separate file.  eg:

```haxe
using cpp.NativeArray;

@:cppFileCode('

std::string CallJson(const char *) { return "hi!"; }

void cppCallFunction(String inFunc, char *returnBuf, int returnLen)
{
   std::string val = CallJson( inFunc.c_str() );
   memcpy(returnBuf, val.c_str(), val.size()+1);
}
')
class Test
{
   @:native("cppCallFunction")
   extern static function cppCallFunction(invokeJson:String, returnBuf:cpp.Pointer<cpp.Char>, returnLength:Int):Void;

   public static function callFunction(invokeJson:String, returnBuf:cpp.Pointer<cpp.Char>, returnLength:Int):Void {
      cppCallFunction(invokeJson, returnBuf, returnLength);
   }


static function main() {
      var buffer = new Array< cpp.Char >();
      buffer[10] = 0;
      callFunction("jello", buffer.address(0), 10);
      trace(buffer);
	}
}
```

**Comment by intoxopox** [comment]
Thx! Good ideas.
