### ISSUE TITLE
IntMap<Int64> does not work with hxcpp and Haxe 3.2.0

### ISSUE THREAD

**Issue by Jens-G** [HaxeFoundation/haxe#4130]
This code

```
import haxe.Int64;
import haxe.ds.IntMap;

class Main {
    static function main() {
        var test = new IntMap<Int64>();
        test.set( 42, Int64.make(42,24));
    }
}
```

worked with Haxe 3.1.3 but leads to the following with Haxe 3.2.0 + HXCPP

```
./src/Main.cpp(39) : error C2668: 'haxe::ds::IntMap_obj::set': ambiguous call to overloaded function
        include\haxe/ds/IntMap.h(60): could be 'void haxe::ds::IntMap_obj::set(int,String)' 
        include\haxe/ds/IntMap.h(59): or "void haxe::ds::IntMap_obj::set(int,double)"
        include\haxe/ds/IntMap.h(58): or "void haxe::ds::IntMap_obj::set(int,float)"
        include\haxe/ds/IntMap.h(57): or "void haxe::ds::IntMap_obj::set(int,unsigned int)"
        include\haxe/ds/IntMap.h(56): or "void haxe::ds::IntMap_obj::set(int,int)"
        include\haxe/ds/IntMap.h(55): or "void haxe::ds::IntMap_obj::set(int,unsigned short)"
        include\haxe/ds/IntMap.h(54): or "void haxe::ds::IntMap_obj::set(int,short)"
        include\haxe/ds/IntMap.h(53): or "void haxe::ds::IntMap_obj::set(int,signed char)"
        include\haxe/ds/IntMap.h(52): or "void haxe::ds::IntMap_obj::set(int,unsigned char)"
        include\haxe/ds/IntMap.h(51): or "void haxe::ds::IntMap_obj::set(int,char)"
        include\haxe/ds/IntMap.h(50): or "void haxe::ds::IntMap_obj::set(int,bool)"
        include\haxe/ds/IntMap.h(49): or "void haxe::ds::IntMap_obj::set(int,null)"
        include\haxe/ds/IntMap.h(45): or "Void haxe::ds::IntMap_obj::set(int,Dynamic)"
        include\haxe/ds/IntMap.h(63): or "Void haxe::ds::IntMap_obj::set<cpp::Struct<cpp::Int64,cpp::Int64Handler>>(Dynamic &,const VALUE &)"
        with
        [
            VALUE=cpp::Struct<cpp::Int64,cpp::Int64Handler>
        ]
        while trying to match the argument list '(int, cpp::Struct<cpp::Int64,cpp::Int64Handler>)'

__files__.cpp
Error: Build failed
Build halted with errors (haxe.exe).
Done(1)

```

**Comment by Simn** [comment]
I'm not sure if that should be allowed by variance rules, but it should certainly not give a native compiler exception.

**Comment by Simn** [comment]
Oh I misread the issue, using Int64 as a value (not key) should certainly work.
