### ISSUE TITLE
Issue 482 - compilation error on haxedoc - haxe

### ISSUE THREAD

**Issue by issuesbot** [HaxeFoundation/haxe#482]
<i>[Google Issue #482 : https://code.google.com/p/haxe/issues/detail?id=482]</i>
 <i>by dsd...@gmail.com, at 28/08/2011, 14:31:31</i>
<b>What steps will reproduce the problem?</b>
1. haxe haxedoc.hxml 

What is the expected output? 
clean compile. (broken since f57b1055709c78350d018384ded04c18dbbb89c6?)

What do you see instead?
c:\devel\haxe\std\tools/haxedoc/Main.hx:97: characters 50-83 : String should be haxe.io.Bytes
c:\devel\haxe\std\tools/haxedoc/Main.hx:97: characters 50-83 : For function argument 's'
c:\devel\haxe\std\tools/haxedoc/Main.hx:109: characters 18-21 : haxe.io.Bytes should be String
c:\devel\haxe\std\tools/haxedoc/Main.hx:109: characters 18-21 : For function argument 's' 

<b>Please provide any additional information below.</b>
(patch attached)
