### PR TITLE
Github actions

### PR DESCRIPTION
**Pull request by RblSb**
Same CI duration without painful setup :shipit:

About fails:
- [x] JS on Linux: fails on [server test](https://github.com/HaxeFoundation/haxe/blob/development/tests/server/src/cases/display/issues/Issue9087.hx#L13)
- [x] Lua on Windows fails same as in #5024 (disabled)
- [x] HL: `hashlink/src/module.c(352) : FATAL ERROR : Failed to load library ssl.hdll` on every platform. (ssl lib is not implemented outside of win32?)

Other problems:
- Because GH Actions currently doesn't have anchors/template and job-file dependency support i use simple preprocessor script to replace `@import path/file` in main file.
- I don't know how to install Neko from binary on Unix, it fails on haxelib setup. So Neko is downloaded from package managers.

Test results here: https://github.com/RblSb/haxe/actions/runs/105680989

### CODE REVIEW

File: extra/github-actions/Main.hx [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+import sys.io.File;
+import haxe.io.Path;
+using StringTools;
+
+class Main {
+
+	static final matchImport = ~/^([ \t]*)@import (.+)$/gm;
+	static final matchRunnable = ~/^([ \t]*)jobs:/gm;
+
+	static function main():Void new Main();
```
Comment (Aurel300) [inline extra/github-actions/Main.hx]: Why create an instance? Could just paste the code from `new` here.

File: extra/github-actions/build-mac.yml [hunk 2]
```diff
@@ -0,0 +1,33 @@
+- name: Install dependencies
+  run: |
+    set -ex
+    brew update || brew update || brew update
```
Comment (Aurel300) [inline extra/github-actions/build-mac.yml]: 🤔

File: extra/github-actions/install-neko.yml [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+    $DOWNLOADDIR="./temp"
+    new-item -Name $DOWNLOADDIR -ItemType directory
+    Invoke-WebRequest https://build.haxe.org/builds/neko/$env:PLATFORM/neko_latest.zip -OutFile $DOWNLOADDIR/neko_latest.zip
+    Expand-Archive $DOWNLOADDIR/neko_latest.zip -DestinationPath $DOWNLOADDIR
+    $NEKOPATH = Get-ChildItem $DOWNLOADDIR/neko-*-*
+    Write-Host "::add-path::$NEKOPATH"
+    Write-Host "::set-env name=NEKOPATH::$NEKOPATH"
+
+- name: Install Neko using snapshot from S3 (Unix)
+  # if: (!startsWith(env.PLATFORM, 'windows'))
```
Comment (Aurel300) [inline extra/github-actions/install-neko.yml]: Stale comment?

File: extra/github-actions/install-neko.yml [hunk 4]
```diff
@@ -0,0 +1,53 @@
...
+    # sudo mkdir -p /usr/local/bin
+    # sudo mkdir -p /usr/local/lib/neko
+    # sudo ln -s $NEKOPATH/{neko,nekoc,nekoml,nekotools}  /usr/local/bin/
+    # sudo ln -s $NEKOPATH/libneko.*                      /usr/local/lib/
+    # sudo ln -s $NEKOPATH/*.ndll                         /usr/local/lib/neko/
+    # sudo ln -s $NEKOPATH/nekoml.std                     /usr/local/lib/neko/
+    # sudo ln -s $NEKOPATH/include/*.h                    /usr/local/include/
+    # set +x
+    # echo "::add-path::$NEKOPATH"
+    # echo "::set-env name=NEKOPATH::$NEKOPATH"
```
Comment (Aurel300) [inline extra/github-actions/install-neko.yml]: And here?

File: extra/github-actions/workflows/main.yml [hunk 5]
```diff
@@ -0,0 +1,179 @@
...
+    runs-on: windows-latest
+    env:
+      PLATFORM: windows64
+      TEST: ${{matrix.target}}
+      HXCPP_COMPILE_CACHE: ~/hxcache
+      ARCH: 64
+    strategy:
+      fail-fast: false
+      matrix:
+        # TODO. Lua/flash has never been enabled on our AppVeyor builds.
```
Comment (Aurel300) [inline extra/github-actions/workflows/main.yml]: Flash is probably not so important anymore, but we could investigate Lua on Windows?

File: extra/github-actions/workflows/main.yml [hunk 6]
```diff
@@ -0,0 +1,179 @@
...
+      - uses: actions/checkout@master
+        with:
+          submodules: recursive
+
+      @import install-neko.yml
+      @import build-windows.yml
+
+  windows-build:
+    runs-on: windows-latest
+    # if: false
```
Comment (Aurel300) [inline extra/github-actions/workflows/main.yml]: .

File: extra/github-actions/workflows/main.yml [hunk 7]
```diff
@@ -0,0 +1,179 @@
+name: CI
+on: [push, pull_request]
+
+jobs:
+  windows64-build:
+    runs-on: windows-latest
+    # if: false
```
Comment (Aurel300) [inline extra/github-actions/workflows/main.yml]: .

**Review by Aurel300 — COMMENTED** [review]
I'll have a look at #9199 today. Can you reproduce the `ssl.hdll` failure locally?

File: tests/runci/targets/Flash.hx [hunk 8]
```diff
@@ -64,7 +64,7 @@ class Flash {
 					File.saveContent(mmcfgPath, "ErrorReportingEnable=1\nTraceOutputFileEnable=1");
 				}
 				switch (ci) {
-					case AzurePipelines:
+					case AzurePipelines, GithubActions:
```
Comment (Aurel300) [inline tests/runci/targets/Flash.hx]: Let's use `AzurePipelines | GithubActions` in modern Haxe style \o/

File: extra/github-actions/build-windows.yml [hunk 9]
```diff
@@ -0,0 +1,50 @@
...
+    & "$($env:CYG_ROOT)/bin/bash.exe" @('-lc', 'echo "$OLDPWD"')
+    & "$($env:CYG_ROOT)/bin/bash.exe" @('-lc', 'cd "$OLDPWD" && tar -C / -xvf libmbedtls.tar.xz')
+    & "$($env:CYG_ROOT)/bin/bash.exe" @('-lc', 'cd "$OLDPWD" && tar -xf opam.tar.xz')
+    & "$($env:CYG_ROOT)/bin/bash.exe" @('-lc', 'cd "$OLDPWD" && bash opam${ARCH}/install.sh')
+    & "$($env:CYG_ROOT)/bin/bash.exe" @('-lc', 'opam init mingw "https://github.com/fdopen/opam-repository-mingw.git#opam2" --comp 4.07.0+mingw${ARCH}c --switch 4.07.0+mingw${ARCH}c --auto-setup --yes 2>&1')
+    & "$($env:CYG_ROOT)/bin/bash.exe" @('-lc', 'opam update --yes 2>&1')
+    & "$($env:CYG_ROOT)/bin/bash.exe" @('-lc', 'cd "$OLDPWD" && opam pin add haxe . --kind=path --no-action --yes 2>&1')
+    & "$($env:CYG_ROOT)/bin/bash.exe" @('-lc', 'opam install haxe --deps-only --yes 2>&1')
+    & "$($env:CYG_ROOT)/bin/bash.exe" @('-lc', 'opam list')
+    & "$($env:CYG_ROOT)/bin/bash.exe" @('-lc', 'ocamlopt -v')
```
Comment (Aurel300) [inline extra/github-actions/build-windows.yml:28]: Maybe we could try to use the [`shell` syntax](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell) here, so we don't have to have this ugly chain of run commands? Specify the CygWin `bash` as the shell with something like `shell: $($env:CYG_ROOT)/bin/bash.exe -lc {0}`, if that works?

File: extra/github-actions/install-neko.yml (hunk 4 above)
Comment (RblSb) [reply extra/github-actions/install-neko.yml]: I just thought if something wrong can be found here to save ~30 seconds on build+test for linux/macos with manual neko installation, but that's complicated

File: tests/runci/targets/Flash.hx (hunk 8 above)
Comment (RblSb) [reply tests/runci/targets/Flash.hx]: Hey, i thought `comma` is added after to have less overlap with `bitwise OR` in switches ;)

File: extra/github-actions/build-windows.yml (hunk 9 above)
Comment (RblSb) [reply extra/github-actions/build-windows.yml:28]: Seems like you cannot use `path/something` for `shell: somebin` and only add binary to PATH first. But because there is no thing to prepend path, i cannot override `C:\Program Files\Git\bin\bash.exe` and this doesn't work.

**Comment by RblSb** [comment]
Lua on Windows fails same as in #5024
See https://github.com/RblSb/haxe/runs/524457120?check_suite_focus=true#step:13:62

**Comment by Aurel300** [comment]
See #9262 for a fix of the Unicode issue.

**Comment by Aurel300** [comment]
Now merged, so please rebase to hopefully fix Mac. The important line for the CI is:

https://github.com/HaxeFoundation/haxe/pull/9262/files#diff-fec826feae04e51c0d94076385408bdcR178-R180

As for Lua, I guess PCRE has to be installed on its own before `librex-pcre`?

**Comment by jdonaldson** [comment]
regarding pcre, I ran into this same problem.  I resolved it by simply running the pcre header installation early in the RunCI class.  

I haven't looked through this new build pipeline in any detail... are c libraries built *after* haxe related library installations for some reason?   If they are, what's a good way forward?  Maybe some kind of pre-build phase for targets like Lua?

**Comment by RblSb** [comment]
@jdonaldson you mean in `runci/targets/Lua`? I see only pcre installation for Linux/MacOS, can you point to Windows stuff?

**Comment by jdonaldson** [comment]
Sorry, not windows specifically.  I was referring to early efforts at running minimalist CI builds without libpcre.

It seems like one easy way forward is to use the pcre libraries provided by hxcpp.  I'm not fluent with Windows, but maybe @hughsando might have some initial tips.

**Comment by Simn** [comment]
What is the status here? I don't want the efforts already made to go to waste.

**Comment by hughsando** [comment]
Hxcpp does not actually build a libpcre library, but it has everything you need to do so.  So it could be something like download/install some version of hxcpp, then run hxcpp on some reasonably simple build.xml file and get a library that you could link against.  It does take a little while to build this particular library (30 seconds?) - not sure how you want to integrate this.

**Comment by RblSb** [comment]
https://github.com/RblSb/haxe/actions/runs/93630892
Mac sys targets still have problems, windows/linux `js` are failing now.
Can reproduce hl problem on mac (10.14), do not have much ideas still.

File: .github/workflows/main.yml [hunk 10]
```diff
@@ -0,0 +1,735 @@
...
+    runs-on: macos-latest
+    env:
+      PLATFORM: mac
+      OPAMYES: 1
+    steps:
+      - uses: actions/checkout@master
+        with:
+          submodules: recursive
+
+      - name: Install Neko using snapshot from S3 (Windows)
```
Comment (Aurel300) [inline .github/workflows/main.yml]: It would be nice if these weren't even generated when they cannot ever match. It results in some noise in the actual run logs.

File: .github/workflows/main.yml [hunk 11]
```diff
@@ -0,0 +1,735 @@
...
+      
+      - name: Install homebrew packages
+        if: matrix.BREW_PACKAGES
+        run: brew install ${{matrix.BREW_PACKAGES}}
+      
+      - name: Test
+        run: |
+          # LC_CTYPE=C
+          # LANG=C
+          haxe RunCi.hxml
```
Comment (Aurel300) [inline .github/workflows/main.yml:615]: I commented on this in #9262, you need to add a line to disable tests which are invalid on Mac:

https://github.com/HaxeFoundation/haxe/blob/2b6424c1a21cc4d19474ef51dc8eac66b9ce220f/azure-pipelines.yml#L178-L180

**Comment by nadako** [comment]
Let's have this! \o/

**Comment by Aurel300** [comment]
I thought @RblSb still needed to address the Mac FS problem. But I see the last force push somehow had a CI pass, although it can not be inspected anymore … What happened?

File: .github/workflows/main.yml (hunk 11 above)
Comment (RblSb) [reply .github/workflows/main.yml:615]: Thanks for hint, head post updated

**Comment by Simn** [comment]
I still don't fully understand what this does. Am I supposed to just merge this and expect somebody to take care of it. :)

**Comment by RblSb** [comment]
I did it for myself mostly, because setting up Azure CI for forks is problematic. If you fork repo on GitHub with GitHub CI - it just works for you. But there is still [Linux js fail](https://github.com/RblSb/haxe/runs/678112339?check_suite_focus=true#step:11:466), have no idea what is wrong. Btw, i can remove Haxe script from this PR, because there is no more code duplication in compiled yaml file.

**Comment by nadako** [comment]
I'd say let's merge this and figure out JS issues later on `development`. I think the good plan is to stabilize Github CI and drop azure in favor of it after everything works.

**Comment by Simn** [comment]
Alright then, let's see how this goes!
