### ISSUE TITLE
Unnecessary casts added by abstracts' `this`

### ISSUE THREAD

**Issue by waneck** [HaxeFoundation/haxe#4045]
It seems that `this` on abstracts are now being cast to the underlying type itself.

The problem is that in some cases, this cast will interfere with the underlying expression. For example, in the case of C# struct / hxcpp `@:structAccess`

Here's one example where this fails:
```haxe
class Main
{
	static function main()
	{
		var t = new Test();
		t.a = 10;
	}
}

abstract Test(TestClass)
{
	inline public function new()
	{
		this = new TestClass(0);
	}

	public var a(get,set):Int;

	inline private function get_a()
	{
		return this.a;
	}

	inline private function set_a(v:Int)
	{
		return this.a = v;
	}
}

@:nativeGen @:struct class TestClass
{
	public var a:Int;

	public function new(av)
	{
		this.a = av;
	}
}
```

compiled with `-cs cs -main Main` fails with `src/Main.cs(28,31): error CS0131: The left-hand side of an assignment must be a variable, a property or an indexer`

This fails because on structs, the left-side of the assignment expression must be an actual variable. In hxcpp / g++, the error is more clear: `using temporary as lvalue [-fpermissive]`

I could fix it on the C# side, but I'd feel very uncomfortable about fixing it on hxcpp, specially since sometimes the AST type differs from the type as seen by the C++ compiler in hxcpp.

**Comment by waneck** [comment]
Note that this can be seen as a regression - as the code above works on 3.1

**Comment by Simn** [comment]
The AST looks fine to me:

```
[Binop:Int]
	[Field:Int]
		[Cast:TestClass] [Local t(2601):Test]
		[FInstance:Int]
			TestClass
			a
	=
	[Const 10:Int]
```

That cast is not unnecessary to the typer because it casts from Test (outside) to TestClass (inside). This was a deliberate change which fixed like 5 different issues. It might be unnecessary from a generator point of view if the abstract is followed to its underlying type, but that's something the generators should take care of.

**Comment by Simn** [comment]
Please tell me if you agree.

**Comment by waneck** [comment]
I guess there's nothing to be done here indeed
