### ISSUE TITLE
regression in Java

### ISSUE THREAD

**Issue by fponticelli** [HaxeFoundation/haxe#4460]
This code worked until past friday (it works on 3.2):

```
  inline public function slice(pos : Int, ?end : Int) : Set<T>
    return new Set(this.slice(pos, end))
```

It now generates:

```
	public static haxe.root.Array<T> slice(haxe.root.Array<T> this1, int pos, java.lang.Object end)
	{
		//line 96 "/Users/francoponticelli/projects/thx.core/src/thx/Set.hx"
		{
			//line 96 "/Users/francoponticelli/projects/thx.core/src/thx/Set.hx"
			haxe.root.Array<T> arr = this1.slice(pos, end);
			//line 96 "/Users/francoponticelli/projects/thx.core/src/thx/Set.hx"
			return ((haxe.root.Array<T>) (arr) );
		}
		
	}
```

That gives the error:

```
src/thx/_Set/Set_Impl_.java:189: error: cannot find symbol
	public static haxe.root.Array<T> slice(haxe.root.Array<T> this1, int pos, java.lang.Object end)
	                                                       ^
  symbol:   class T
  location: class Set_Impl_
src/thx/_Set/Set_Impl_.java:189: error: cannot find symbol
	public static haxe.root.Array<T> slice(haxe.root.Array<T> this1, int pos, java.lang.Object end)
	                              ^
  symbol:   class T
  location: class Set_Impl_
src/thx/_Set/Set_Impl_.java:194: error: cannot find symbol
			haxe.root.Array<T> arr = this1.slice(pos, end);
			                ^
  symbol:   class T
  location: class Set_Impl_
src/thx/_Set/Set_Impl_.java:196: error: cannot find symbol
			return ((haxe.root.Array<T>) (arr) );
			                         ^
  symbol:   class T
  location: class Set_Impl_
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
4 errors
Compilation error
Native compilation failed
```

**Comment by fponticelli** [comment]
Very likely related to #4459

**Comment by waneck** [comment]
The test made fails on flash / js - seems to be a problem with `slice`
ping @Simn

**Comment by ncannasse** [comment]
Maybe passing null as length does not behave the same as not passing an arg
?

**Comment by andyli** [comment]
```haxe
class Test {
	static function myslice(start:Int, ?end:Int)
		return [1,2,3,4].slice(start, end);

	static function main(){
		trace([1,2,3,4].slice(1));
		trace([1,2,3,4].slice(1, null));
		trace(myslice(1));
		#if js
		trace([1,2,3,4].slice(1, untyped __js__("undefined")));
		#end
	}
}
```

swf prints:
```
[2,3,4]
[]
[]
```

JS in IE8 prints:
```
[2,3,4]
[]
[]
[]
```

JS in other modern browsers print:
```
[2,3,4]
[]
[2,3,4]
[2,3,4]
```

Maybe we need to add `HxOverrides.slice`?

**Comment by ncannasse** [comment]
I think that changing the slice specification is the best way here.
