### PR TITLE
[cpp] Fix arg type vs name mismatch

### PR DESCRIPTION
**Pull request by tobil4sk**
This fixes a regression from #11785 (from the PR branch it is commit 07a4c6f48c8561d19c547fcc960f3a0c234847d5 specifically). See line 678 in gencpp.ml in that commit, where `let pair = ... in snd pair` was incorrectly refactored to `let n, _ = ... in n`

This results in the type of an argument being generated instead of the name, which results in broken c++ code:
```
Error: ./src/Main.cpp: In static member function ‘static void Main_obj::nativeFunc(int)’:
./src/Main.cpp:28:24: error: expected primary-expression before ‘int’
   28 |         (void)::nativeFunc(int);
      |
```
It should be generating `(void)::nativeFunc(a);` instead.

### CODE REVIEW

**Comment by tobil4sk** [comment]
The tests are currently failing with:
```
Running haxe projects/Pull12448/compile.hxml
/usr/bin/ld: ~/hxcache/haxe/10/42714a67b666bc1f95898cc87833c7.o: in function `Main_obj::__GetStatic(String const&, Dynamic&, hx::PropertyAccessMode)':
Main.cpp:(.text+0x91): undefined reference to `Main_obj::native_dyn()'
collect2: error: ld returned 1 exit status
Error: Build failed
```

This is caused by a separate regression: #12449
