### ISSUE TITLE
Haxe 3.3 vs Haxe 3.4 issues with macro-generated build fields

### ISSUE THREAD

**Issue by Glidias** [HaxeFoundation/haxe#5996]
I am using a Windows 7 OS. When running HaxeDevelop with version 3.4 SDK (instead of version 3.3), I have the following issue when I attempt to inspect a macro-generated function field with F4. 

By default, my macro-generated function field `_getAllProducts` position is set to an already existing `static function getAllProducts()` method  position in the class `haxevx.vuex.examples.shoppingcart.Products.ProductListDispatcher` in my  `VuexMacros` implementation for `buildActions -> buildActionCalls()` https://github.com/Glidias/haxevx/blob/594b4ba758910670ae3d5f7be50574fcb43268b5/src/haxevx/vuex/core/VuexMacros.hx#L1086

https://github.com/Glidias/haxevx/blob/594b4ba758910670ae3d5f7be50574fcb43268b5/src/haxevx/vuex/examples/shoppingcart/modules/Products.hx#L45

How to replicate the issue:

Go to the following location at `haxevx.vuex.examples.shoppingcart.components.ProductListVue` and look for the `Created()` function.
https://github.com/Glidias/haxevx/blob/594b4ba758910670ae3d5f7be50574fcb43268b5/src/haxevx/vuex/examples/shoppingcart/components/ProductListVue.hx#L44

I hit F4 on the `_getAllProducts` label, but somehow, I get the following error in the Output.

`src/haxevx/vuex/examples/shoppingcart/components/ProductListVue.hx:35: characters 2-30 : Call expected.`

But for some strange reason, it seems to think that the expression is not a function call invokation for `dispatcher._getAllProducts` in my `ProductListVue`??

When compiling, the error output is removed and it works fine.

Expected result is supposed to jump to the static `ProductListDispatcher.getAllProducts` function when i hit F4 on that `_getAllProducts` field under `dispatcher._getAllProducts(store)`.

It works fine on Haxe 3.3, HaxeDevelop, as long as the function brackets `()` are included in fully.

When running the same thing on Visual Studio Code with Haxe 3.4  add-on (since Haxe 3.4 is required), I don't have this type-hinting issue with F12 or Ctrl+Click though....and I can quickly jump to the coorresponding static method according to expected result, even without function brackets `()` being typed in (ie. just the name being spelled out fully). 

_______

On a sidenote, when I compile the HaxeVx Vuex store example with Haxe 3.4 with `-D production` flag on, the macro code is supposed to replace the underscored action method calls like `dispatcher._getAllProducts(store, ...params)`, to  something like `this.$store.commit( macroDerivedStringFromClassField, ....params)`. However, for version 3.4 of Haxe, it  becomes `this.$store;` in the outputted code (as if no function call is invoked??).  It works fine in 3.3 though. Could this issue be related to the above as well? You can refer to the expression replacement implementation at `VuexMacros.checkToRemapVuexDispatch`, where the `startExpr` refers to the expression of each given function body within the current class context: https://github.com/Glidias/haxevx/blob/594b4ba758910670ae3d5f7be50574fcb43268b5/src/haxevx/vuex/core/VuexMacros.hx#L88

______

What do you think is different about 3.3 vs 3.4 with regards to the above issues?

**Comment by Glidias** [comment]
Sorry, false alarm. Was using "Windows Open with...". with hxml file extension and it was using an inconsistent older version of Haxe.

 Downloaded and tested with latest Haxe 3.4 though, it works fine.
