### PR TITLE
Fix @:generic with multiple calls

### LINKED ISSUE #11608: @:generic compilation error when the function is called multiple times
I discovered that the following code does not compile anymore. I don't know how exactly `@:generic` should work, but it looks very strange that the first call to doF does not yield any error, but the followings call failed with a message that does not make much sense.
First bad commit https://github.com/HaxeFoundation/haxe/commit/3c07ce1569df6daf03a4fa4a8ab520af5273759a.

```haxe
using Test.ArrayExtension;
class Test {
	public static function doF2<T>(f: T -> Float) : T {
		var arr = [];
		arr.doF(f); // Ok
		arr.doF(f); // error: doF2.T should be doF2.T Cannot create field doF_doF2_T due to type mismatch
		return arr.doF(f); // error: doF2.T should be doF2.T Cannot create field doF_doF2_T due to type mismatch
	}

	static public function main() {
	}
}

class ArrayExtension {
	@:generic
	public static function doF<T>(array: Array<T>, f: T -> Float) : T {
		return null;
	}	
}
```

### PR DESCRIPTION
**Pull request by kLabz**
... and likely break something else

I'm reverting part of 3c07ce1569df6daf03a4fa4a8ab520af5273759a here, and CI is fine with it which mostly tells me we're missing some tests.

Closes #11608

### CODE REVIEW

**Comment by Simn** [comment]
I'm fine with merging this if we can't find any issues. I don't remember what exactly I originally fixed with that commit.

**Comment by kLabz** [comment]
Couldn't find any issue with local projects
