### ISSUE TITLE
"error: could not convert..." after 3.2.1 -> 3.4.2 upgrade

### ISSUE THREAD

**Issue by IBwWG** [HaxeFoundation/haxe#6121]
The following code compiled fine (transpiled to cpp via `openfl build linux`, hxcpp 3.4.49) on my 64-bit Linux Mint box, with Haxe 3.2.1 and Neko 2.1.0:

```haxe
add(new Speech(BalloonStyle.TALK, mathilda, 1019, 107, 213, ["Yay!  Look at all the fairy dust they gave me!", "Youpeeee!"], 3, function () {
 	add(new Speech(BalloonStyle.TALK, mathilda, 1019, 107, 213, ["This is so fun!\nC'mon, Willy...\ncatch up!"], 3,
		timer.start.bind(3, postMiniGame)
	));
	Main.fadeOutMusic(null, 3);
}));
```

After the upgrade, without any changes, I attempted a recompile, and got this error:

```
Error: ./src/minigames/CollectFairyDustState.cpp: In member function ‘flixel::util::FlxTimer minigames::CollectFairyDustState_obj::set_points(int)::_hx_Closure_1::_hx_run()::_hx_Closure_0::_hx_run()’:
./src/minigames/CollectFairyDustState.cpp:626:53: error: could not convert ‘Dynamic::operator()(const Dynamic&, const Dynamic&, const Dynamic&)(Dynamic(3), ((minigames::CollectFairyDustState_obj::set_points(int)::_hx_Closure_1::_hx_run()::_hx_Closure_0*)this)->minigames::CollectFairyDustState_obj::set_points(int)::_hx_Closure_1::_hx_run()::_hx_Closure_0::a2, Dynamic(null())).Dynamic::operator int()’ from ‘int’ to ‘flixel::util::FlxTimer {aka hx::ObjectPtr<flixel::util::FlxTimer_obj>}’
 HXLINE( 175)      return ( (int)(f((int)3,a2,null())) );
                                                     ^
```

If I changed the inner `add()` call to use a function wrapper rather than `.bind()`, it compiles on 3.4.2:

```haxe
	add(new Speech(BalloonStyle.TALK, mathilda, 1019, 107, 213, ["This is so fun!\nC'mon, Willy...\ncatch up!"], 3,
		function () {timer.start(3, postMiniGame);}
	));
```

I found it interesting that just this one spot in the entire project was all that broke, considering I use `.bind` a total of 42 times throughout it, including in an extremely similar context:

```haxe
add(new Speech(BalloonStyle.TALK, mathilda, 975, 580, 184, ["I found the Lost Piece!"], 3, function(){
	add(new Speech(BalloonStyle.TALK, willy, 872, 518, 293, ["So that's what Atlantis looks like!"], 3,
		timer.start.bind(3, postMiniGame)
	));
}));
```

I'm failing to see the difference between that code, which works without modification on both 3.2.1 and 3.4.2, and the code at the top, which needed to be changed for 3.4.2.  But I thought I should at least post my findings and the workaround that worked for me.

**Comment by IBwWG** [comment]
Updating to hxcpp 3.4.64 changes the build order somehow so that the error occurs much later in the build process, but the same error still occurs.

**Comment by hughsando** [comment]
This looks like the typing of the TReturn field that I changed.
In which case, the difference is probably due to the return type of the enclosing function rather than any differences between the lines of code themselves.
If you could post a small example, that would be great.
If not, the function declaration (args and return type_ of  timer.start and add and the function that works and the function that does not would really help.

**Comment by IBwWG** [comment]
Sorry for the delay.  I'm confused--the lines of codes refer to the same function, so it naturally has the same return type...where would the difference be?  Anyway given that you've closed it, do you still want the function declaration or is it moot at this point?

**Comment by hughsando** [comment]
No thanks - I managed to work something out.
The difference is in the enclosing function (surrounding what you have shown here).  If the closure is inside a function that returns an int, you get this issue.

**Comment by IBwWG** [comment]
Super, and thanks for satisfying my curiosity.  Glad you were able to figure it out so fast!
