### ISSUE TITLE
[cpp] "not a member of" with safe cast to interface

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5705]
This is a **regression** - compiles fine on 3.2.1, but errors on latest Haxe (a7b39dd) - happens on rc1 as well though, so not newly introduced.

```
./src/Main.cpp(47): error C2039: 'z': is not a member of 'BaseClass_obj'
```

```haxe
class Main {
	public static function main() {}

	static function foo(baseClass:BaseClass):Int {
		return cast(baseClass, IInterface).z;
	}
}

class BaseClass {}

interface IInterface {
	public var z:Int;
}

class ImplementingClass extends BaseClass implements IInterface {
	public var z:Int;
}
```

**Comment by mikeevmm** [comment]
Is there a stable version of Haxe I can grab with this bugfix applied?

**Comment by Simn** [comment]
No, best you can do is get a nightly from builds.haxe.org.

**Comment by mikeevmm** [comment]
For future reference, this can be worked around in `Haxe 3.3.0-rc1` using `Std.is` and unsafe casts, i.e.:

```haxe
if (Std.is(object, IInterface)) (cast object).interfaceProperty();
```

**Comment by Gama11** [comment]
IIRC, you can just work around this by splitting the expression into two lines:

```haxe
var foo = cast(baseClass, IInterface);
return foo.z;
```

**Comment by mikeevmm** [comment]
Didn't seem to work.
