### ISSUE TITLE
[cs] Pointer detection broken

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#11527]
https://github.com/HaxeFoundation/haxe/commit/9e7a820a587fb08d3ad385d4a329f80e3977c81e broke the C# pointer detection with some changes like this in the dump:

```
< 	[Cast:cs.PointerAccess<unit._TestCSharp.SomeStruct>] [Local addr(45777):cs.Pointer<unit._TestCSharp.SomeStruct>:cs.Pointer<unit._TestCSharp.SomeStruct>]
---
> 	[Cast:unit._TestCSharp.SomeStruct] [Cast:cs.PointerAccess<unit._TestCSharp.SomeStruct>] [Local addr(45777):cs.Pointer<unit._TestCSharp.SomeStruct>:cs.Pointer<unit._TestCSharp.SomeStruct>]
```

PointerAccess is a forwarding abstract:

```haxe
@:forward abstract PointerAccess<T>(T) {}
```

The C# generator follows it away to look for the `cs.Pointer` type, but with the new dump the `Cast:unit._TestCSharp.SomeStruct` now gets in the way of that detection.

The problem here is that the new typing is more correct: We cast the abstract to the underlying type, then access its field. I'm not even sure why it wasn't like that before because the `{ e with etype = t }` should also turn the expression into the underlying type.

**Comment by Simn** [comment]
Addressed in https://github.com/HaxeFoundation/haxe/commit/e2e359be130917f06802976532e6af5ab25aca0a. There's now `@:forward.accessOnAbstract` which generates the field access on the abstract instead of the underlying type. I think the way C# handles this is quite clever, so I'd like to still support it. It would be nice to have a more general way to "tag" field access, but I can't really think of anything.

**Comment by Simn** [comment]
C# is still broken, but of course only on Linux and Mac because that seems to be this month's theme.

**Comment by Simn** [comment]
```
< 			return ( (global::haxe.lang.StringExt.charCodeAt(global::haxe.lang.Runtime.toString(global::haxe.lang.Runtime.getField(a, "name", 1224700491, true)), 0)).@value < (global::haxe.lang.StringExt.charCodeAt(global::haxe.lang.Runtime.toString(global::haxe.lang.Runtime.getField(b, "name", 1224700491, true)), 0)).@value );
---
> 			return ( (global::haxe.lang.StringExt.charCodeAt(global::haxe.lang.Runtime.toString(global::haxe.lang.Runtime.getField(((object) (a) ), "name", 1224700491, true)), 0)).@value < (global::haxe.lang.StringExt.charCodeAt(global::haxe.lang.Runtime.toString(global::haxe.lang.Runtime.getField(((object) (b) ), "name", 1224700491, true)), 0)).@value );
```

So it adds `((object) (a) )` casts. While that's certainly weird, I can't immediately tell why it causes a syntax error:

```
/home/runner/work/haxe/haxe/tests/unit/src/unit/issues/Issue9123.hx(8,220): error CS1031: Type expected
/home/runner/work/haxe/haxe/tests/unit/src/unit/issues/Issue9123.hx(8,254): error CS1525: Unexpected symbol `)', expecting `;'
```

**Comment by kLabz** [comment]
Kinda looks like #7200 ?

**Comment by Simn** [comment]
I tried dodging the cast altogether if the types are equal, but there's some insanity going on with `>>>` generation that causes loads of `Cannot implicitly convert type 'long' to 'int'. An explicit conversion exists (are you missing a cast?)` errors.

**Comment by Simn** [comment]
Next problem: The compiler comes across this crap:

```haxe
class Task_1<T0> {
    static public var Factory(get,never) : cs.system.threading.tasks.TaskFactory_1<T0>;
}
```

This fails since https://github.com/HaxeFoundation/haxe/commit/c5f913ca14e0ee424119045cb835c80d79ea9603. I've hacked it so that the type parameter lookup is allowed for `@:libType` classes, but that's a terrible workaround. A better workaround will be the removal of the C# target.

**Comment by Simn** [comment]
Well, I guess I'll close here again because everything is "fixed".
