### PR TITLE
Restore macOS 10.13 (High Sierra) support

### LINKED ISSUE #10723: Haxe 4.2.5 does not work on macOS High Sierra 10.13.6
It installs successfully but when I try to write any command related to Haxe, it gives me this error.
Haxe 4.2.2 does work.

```
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /usr/local/bin/haxe (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /usr/local/bin/haxe (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6
```

### PR DESCRIPTION
**Pull request by justin-espedal**
This restores macOS 10.13 support by ensuring that the pcre code that's linked into Haxe is built from source with the 10.13 deployment target.

This fixes https://github.com/HaxeFoundation/haxe/issues/10723

### CODE REVIEW

**Comment by justin-espedal** [comment]
Since this was only a theoretical fix to the issue, I felt a little iffy about sending a PR and stating that this "restores macOS 10.13 support" as a fact, so I marked it as a draft at first.

I've had the chance to confirm for myself that the binaries this PR produces do run on macOS 10.13, so this is ready to merge.

**Comment by Simn** [comment]
Could you update this PR so that we can check the CI again?

**Comment by justin-espedal** [comment]
I've updated it. 🫡

**Comment by Simn** [comment]
Thank you!
