### ISSUE TITLE
Issue 1824 - CS: Error when a class inherits a method with a generic type parameter - haxe

### ISSUE THREAD

**Issue by issuesbot** [HaxeFoundation/haxe#1824]
<i>[Google Issue #1824 : https://code.google.com/p/haxe/issues/detail?id=1824]</i>
 <i>by JFMu...@gmail.com, at 17/05/2013, 16:42:27</i>
The following code does not compile using Haxe 3.0 RC2 when targeting C#.  
Error : &quot;src/Test.cs(102,31): error CS0111: A member `Test.test&lt;T&gt;(T)' is already defined. Rename this member or use different parameter types&quot;

<pre>class Test implements Foo {
    public static function main() : Void {
        }
    public function test&lt;T&gt;(arg:T) : Void {
        }
    }
</pre>

</b>

<pre>interface Foo {
    function test&lt;T&gt;(arg:T) : Void;
    }
</pre>

</b>
