### ISSUE TITLE
Call to `Void->Void` property does not compile

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#5519]
Following sample compiles and works fine with 3.2.1, but fails to compile with latest 3.3
```haxe
class Test {
  var callbackProperty : Void->Void;
  
  static function main() {
    var t = new Test();
    trace(t.callbackProperty());
  }
  
  function new () {}
}
```
Compilation error:
```
Test.hx:6: characters 10-30 : Cannot use Void as value
```
Same error for static callback properties.

[try-haxe 3.3](http://try-haxe.mrcdk.com/#E7135)
[try-haxe 3.2.1](http://try.haxe.org/#DeB3D)

**Comment by Simn** [comment]
That's intended, you're trying to use the result of a Void-returning function as a value which is not a good idea.

**Comment by MSGhero** [comment]
If `Void` can't be used as a value, then what's going on here?
```haxe
class Test {
    
    static function main() {
        var g = new A<Void>();
        g.test(null);
        g.test2(voidVoid); // Void -> Void should be (Void) -> Unknown<0> For function argument 'f'
        // g.test2(cast voidVoid); // compiles and runs
    }
    
    static function voidVoid():Void { }
}

class A<T> {
    var t:T;
    public function new() { }
    public function test(t:T):Void { this.t = t; }
    public function test2<U>(f:T->U):Void { f(t); }
}
```
I got OP's error because my `<T>` happens to be `Void` in one case, but I can still use `Void`/`null` as a value for `g.test(null)`.

**Comment by nadako** [comment]
>  But I can still use Void/null as a value for g.test(null).

no more on 3.3/git
