### ISSUE TITLE
regression in C#

### ISSUE THREAD

**Issue by fponticelli** [HaxeFoundation/haxe#4459]
This code worked until past friday (it works on 3.2):

```
  inline public function slice(pos : Int, ?end : Int) : Set<T>
    return new Set(this.slice(pos, end))
```

It now generates:

```
public static global::Array<T> slice(global::Array<T> this1, int pos, global::haxe.lang.Null<int> end) {
   {
        global::Array<T> arr = this1.slice(pos, end);
        return ((global::Array<T>) (arr) );
    }			
}
```

That gives the error:

```
src/thx/Set.cs(122,31): error CS0246: The type or namespace name `T' could not be found. Are you missing an assembly reference?
Compilation failed: 1 error(s), 0 warnings
Compilation error
Native compilation failed
```

**Comment by waneck** [comment]
What's "Set"? Can you post a full example?

**Comment by waneck** [comment]
@Simn, is there any reliable way to know if a static function from a `KAbstractImpl` came from a static or a non-static abstract function? I was looking for the first argument being named "this", but this isn't reliable. Help?

**Comment by waneck** [comment]
This isn't reliable = in the above case, it's named `this1` - even though normally it's named `this`

**Comment by waneck** [comment]
@Simn, I was checking for `@:impl`, but that wasn't reliable because of this:
https://github.com/HaxeFoundation/haxe/blob/development/typeload.ml#L2248
and this:
https://github.com/HaxeFoundation/haxe/blob/development/std/Map.hx#L137

This made Maps fail when compiling with `-dce no`

**Comment by Simn** [comment]
You can check if the variable of the first argument has `Meta.This`. The typeload line shouldn't be there but there were some issues with removing it for 3.2.

**Comment by fponticelli** [comment]
`Set` implementation is here: https://github.com/fponticelli/thx.core/blob/master/src/thx/Set.hx
And the full build is here: https://travis-ci.org/fponticelli/thx.core

**Comment by fponticelli** [comment]
Cool, thanks!
