### ISSUE TITLE
[cpp] missing Null<T> conversion operator

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5543]
This is a very recent **regression** (did not happen as of ec3df2e, but happens now with e32f5f1 - haven't bisected the exact commit).

```haxe
class Main {
	public static function main() {
		f1(null);
	}

	static function f1(n:NullableInt)	{
		f2(n.i);
	}

	static function f2(i:Int = 0) {}
}

typedef NullableInt = {
	?i:Int
}
```

Fails with:

```
./src/Main.cpp(38): error C2664: 'void Main_obj::f2(hx::Null<Int>)': cannot convert argument 1 from 'hx::Val' to 'hx::Null<Int>'
./src/Main.cpp(38): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
Error: Build failed
```

Noticed this because Flixel's Travis broke.

**Comment by Simn** [comment]
Bisected to https://github.com/HaxeFoundation/haxe/commit/f769ed11.

**Comment by hughsando** [comment]
This worked out quite well - this should avoid boxing the Int in this case.

**Comment by Gama11** [comment]
Thanks for the quick fix - Flixel's Travis is green again! :+1:
