### ISSUE TITLE
[cpp] Lime CFFI issues in 3.4.1 (cannot convert from 'hx::Object *' to 'String')

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#6103]
Regression, bisected to 029cd1eb9a743. Isolated from `lime.ui.JoyStick` (similar errors happen in `lime.ui.Gamepad`). This breaks 3.4.1 for Flixel (with OpenFL Next) / OpenFL on the cpp target as far as I can tell.

>Error: Main.cpp
./src/Main.cpp(50): error C2440: 'return': cannot convert from 'hx::Object *' to 'String'
./src/Main.cpp(50): note: Constructor for class 'String' is declared 'explicit'

```haxe
class Main {
    static var id:Int;
    static var guid(get,never):String;

    public static function main()
        trace(guid);

    static inline function get_guid()
        return lime_joystick_get_device_guid(id);

    static inline function lime_joystick_get_device_guid(id:Int):Dynamic
        return cffi_lime_joystick_get_device_guid.call(id);

    static var cffi_lime_joystick_get_device_guid:cpp.Callable<StdTypes.Int->cpp.Object> =
        new cpp.Callable<Int->cpp.Object>(cpp.Prime._loadPrime("lime", "lime_joystick_get_device_guid", "io", false));
}
```

**Comment by jgranick** [comment]
We use `:Dynamic` as the return type for string values over CFFI. We use a mixture of `alloc_string` and `alloc_wstring` when returning strings from CFFI.

I'm not sure if we should using `:String` as the return type (and if it would work) or use `:Dynamic` (which is represented as `:cpp.Object` on the C++ target in our macro, due to issues with plain dynamic)

Perhaps `:String` is not actually a `:cpp.Object`?

Anyway, open to suggestions on the right approach if this isn't a bug

**Comment by hughsando** [comment]
This came when I messed with the typing of TCppReturn to try to work around a issue.  If I restore the original:
```ocaml
| TReturn eo ->
            CppReturn(match eo with None -> None | Some e -> Some (retype (cpp_type_of expr.etype) e)), TCppVoid
```
it works as before, but new stuff breaks.

@Simn   I think the real issue is the typing of the "TReturn".  Is it the function return type? I guess it would be void otherwise, since you can't do "var x = return ...".
The following code:
```haxe
class Test
{
   var testVal:Test;
   var testProp(get,null):Test;

   function get_testProp() return testVal;
   public function new()
   {
      trace(testProp);
   }

   public static function main() new Test();
}
```
Generates the dump:
```
	function get_testProp[Function:Void -> Test]
		[Block:Dynamic]
			[Return:Dynamic]
				[Field:Test]
					[Const:Test] this
					[FInstance:Test]
						Test
						testVal
```
Note the typing of Return:Dynamic - but should it be Test ?

**Comment by Simn** [comment]
TReturn has always been typed as Dynamic. You're supposed to look at the value it returns to figure out the return type. I don't remember why it is like that, but it was like that when I found it.

**Comment by nadako** [comment]
Isn't that because you can do `var a:String = return 5` and it would be weird to have that return typed as `Int` in a case like this.

**Comment by Simn** [comment]
Right, I think that's the reason. Looks silly in such simple examples, but it makes sense if you have something like a big value-switch in which some cases return.

**Comment by hughsando** [comment]
Ok, I'll have to track "current function return type" if it't not stored anywhere, since this could be different from the type of the eexpr that gets returned (at least, using the typedef hack)

**Comment by hughsando** [comment]
Makes me wonder actually if there is something different about the properties, since it seems to work elsewhere (just using the type of the returned expression).

**Comment by nadako** [comment]
> "current function return type" if it't not stored anywhere

Why wouldn't toplevel `TFunction` expression's `tfunc.tf_type` or even field `TFun` type work here?

**Comment by hughsando** [comment]
Yes - just need to track it to the TReturn expression
