### ISSUE TITLE
[js] Regression with null safety diagnostics

### ISSUE THREAD

**Issue by RblSb** [HaxeFoundation/haxe#11904]
In nightly builds after file resave this error occurs: (no compilation errors). From vshaxe codebase, doesn't happen on interp.
Main.hx:
```haxe
using StringTools;

@:nullSafety
class Main {
	static function main() {}

	static function extractReturnType(hint:String):Void {
		// Null safety: Cannot unify String with { charCodeAt : Int -> Int }
		for (i => code in hint) {}
	}
}
```

```hxml
-cp src
-main Main
--js bin/main.js
```

**Comment by RblSb** [comment]
Minimized example: `StringTools.unsafeCodeAt("foo", 0)`.

This basically inlines `return (cast s).charCodeAt(index)`:
https://github.com/HaxeFoundation/haxe/blob/development/std/StringTools.hx#L504

Not really a regression, happens since https://github.com/HaxeFoundation/haxe/commit/c4cc470360fb8cfbd57613251f8afca5f4c84b3b

Unification errors here on `TAbstract(Null, [TAbstract(Int, [])])` and `TAbstract(Int, [])` comparison (idk how is first type is maked here).
https://github.com/HaxeFoundation/haxe/blob/development/src/typing/nullSafety.ml#L233

Interestingly, this error does not happen if you copy `unsafeCodeAt` function to Main class and call it. But error will happen on file resave if you create separate class and call it like `Tools.unsafeCodeAt("foo", 0)`, so it looks like server cache problem related to modules, and not a null safety cache thing.

**Comment by kLabz** [comment]
Yeah it's a hxb cache vs null safety issue; it goes away with `-D disable-hxb-cache`.

**Comment by kLabz** [comment]
Dump:
```haxe
@:nullSafety
class Main {

	@:keep
	static function main() {}

	static function extractReturnType(hint:String) {
		var _g_offset = 0;
		var _g_s = hint;
		while ((_g_offset < _g_s.length)) {
			var _g_key = _g_offset;
			var _g_value = cast _g_s.charCodeAt(_g_offset ++);
			var i = _g_key;
			var code = _g_value;
		};
	}
}
```

```
@:nullSafety
class Main {

	@:keep
	static function main[Function:() -> Void] [Block:Void]

	static function extractReturnType[Function:(hint : String) -> Void]
		[Arg hint<0>(VUsedByTyper):String]
		[Block:Void]
			[Var _g_offset<0>:Int] [Const:Int] 0
			[Var _g_s<0>:String] [Local hint(0):String:String]
			[While:Void]
				[Parenthesis:Bool]
					[Binop:Bool]
						[Local _g_offset(0):Int:Int]
						<
						[Field:Int]
							[Local _g_s(0):String:String]
							[FInstance:Int]
								String
								length:Int
				[Block:Dynamic]
					[Var _g_key<0>:Int] [Local _g_offset(0):Int:Int]
					[Var _g_value<0>:Int]
						[Call:Int]
							[Field:Int -> Int]
								[Cast:{ charCodeAt : Int -> Int }] [Local _g_s(0):String:String]
								[FAnon:Int -> Int] charCodeAt:Int -> Int
							[Unop:Int]
								++
								Postfix
								[Local _g_offset(0):Int:Int]
					[Var i<0>:Int] [Local _g_key(0):Int:Int]
					[Var code<0>:Int] [Local _g_value(0):Int:Int]
}
```

Note that copying that generated code from above dump does not trigger the issue. I think some var type might not be correctly initialized?

Also `[Cast:{ charCodeAt : Int -> Int }]` and `[FAnon:Int -> Int] charCodeAt:Int -> Int` don't match `String.charCode` signature (return is `Null<Int>`) 

cc @Simn 

Another lead could be that `++` unop? 🤔

**Comment by kLabz** [comment]
Right, that was about `StringIterator` using `StringTools.unsafeCodeAt` which inlines `(cast s).charCodeAt(index);` 🤦 

Still, hxb should probably better recover those untyped casts
