### PR TITLE
[js] improve TypedArray

### PR DESCRIPTION
**Pull request by terurou**

### CODE REVIEW

**Comment by haxiomic** [comment]
Hey @terurou, this looks good, could you try compiling a few of the major typedarray libraries like Kha and OpenFL to check for any errors?

**Comment by terurou** [comment]
I tried compiling in Kha. Maybe there was no problem. But I haven't used Kha, so I'm not sure if the steps below are correct.

Checkout Kha head
```
git clone --recursive https://github.com/Kha-Samples/Empty.git
cd Empty
git submodule update --init --depth 50 --recursive
```

Edit khafile.js
```
let project = new Project('Empty');

project.addSources('Sources');
project.addParameter('--macro include("kfa", true)');

resolve(project);
```

Compile by Kha ( in WSL )
```
HAXE_STD_PATH=./work/haxe/std node Kha/make html5 --krafix "Kha/Kore/Tools/krafix/krafix.exe" --haxe /usr/local/haxe4.0.0-rc.3/haxe
```

**Comment by terurou** [comment]
I can't compile with Lime 7.5.0. (TypedArrays are not used by OpenFL directly.)
I'll fix it.
```
$ HAXE_STD_PATH=../haxe/std haxe build.hxml
/home/terurou/haxelib/lime/7,5,0/src/lime/graphics/ImageBuffer.hx:139: characters 30-34 : lime.utils.UInt8Array should be Null<Int>
/home/terurou/haxelib/lime/7,5,0/src/lime/graphics/ImageBuffer.hx:139: characters 30-34 : For optional function argument 'elements'
/home/terurou/haxelib/lime/7,5,0/src/lime/math/ColorMatrix.hx:96: characters 43-47 : lime.utils.Float32Array should be Null<Int>
/home/terurou/haxelib/lime/7,5,0/src/lime/math/ColorMatrix.hx:96: characters 43-47 : For optional function argument 'elements'
```

**Comment by Gama11** [comment]
That might be https://github.com/openfl/lime/pull/1332.

**Comment by terurou** [comment]
@Gama11 Thanks! openfl/lime#1332 had already resolved this OpenFL compilation error.

Make build.hxml
```
-js dummy.js
-lib lime
-D html5
-D lime_webgl
--macro include("lime.utils")
--macro include("lime.graphics")
--no-output
```

Compile with Lime(git head)
```
git clone --recursive https://github.com/openfl/lime
haxelib dev lime lime 
HAXE_STD_PATH=../haxe/std haxe build.hxml
```

@haxiomic I succeeded in compiling with Kha and OpenFL.

**Comment by haxiomic** [comment]
Amazing, thanks @terurou! LGTM
