### ISSUE TITLE
@:debug trigger compilation error

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#5688]
Our code base for Northgard no longer compiled, saying one class does not have field XXX 

I bisected to a90322964c0d8f4b20146086b87311f7a054ae84 but it took me time to understand this was because our method was tagged with `@:debug`, which is used by flash output to force specific method/class debug infos (while still compiling in release other code parts).

Seems like this now also trigger something that creates a compilation bug

**Comment by Simn** [comment]
Yes yes I should stop overloading metadata...

It's interesting that this causes compilation errors. I suppose it comes from some `s_type` causing an early `follow`.
