### ISSUE TITLE
Unserializer build issue with Haxe 3.4.0

### ISSUE THREAD

**Issue by francoisvn** [HaxeFoundation/haxe#5983]
This build issue started happening when upgrading to Haxe 3.4.0 just now:

```
Error: ./src/haxe/Unserializer.cpp: In member function ‘Dynamic haxe::Unserializer_obj::unserialize()’:
./src/haxe/Unserializer.cpp:329:79: error: ‘_hx_reslove_virtual_array’ was not declared in this scope
 HXLINE( 281)     return (this->cache->set(cachePos,_hx_reslove_virtual_array(a)));
                                                                               ^
```

I am having some issues with unserializing on native targets since Haxe 3.2.1, which I'm still trying to diagnose, but since upgrading Haxe to 3.4.0 (from 3.4.0-rc.2 and prior), the native build breaks as above. It could be an issue in hxcpp, but it was building before so it seems sensible to report here. Happy to provide more details or give output from my side.

**Comment by nadako** [comment]
Could it be that you forgot to update hxcpp?

**Comment by nadako** [comment]
This makes me think that maye Haxe should somehow require a version of hxcpp and output an error if it's incompatible.

**Comment by francoisvn** [comment]
I'm using hxcpp 3.4.43, which seems to be the latest version

**Comment by nadako** [comment]
Looks like this method was added a week ago (https://github.com/HaxeFoundation/hxcpp/commit/2d05c840486685dc52788e7c924541712c358806) and @hughsando has to make a hxcpp release.

**Comment by nadako** [comment]
@francoisvn meahwhile you could install hxcpp from git https://github.com/HaxeFoundation/hxcpp

**Comment by francoisvn** [comment]
Seems like using the very latest hxcpp from git works, and AFAICT it also fixes my other issue with unserializing :)

**Comment by underscorediscovery** [comment]
Note that it seems this is still spelt incorrectly @hughsando `_hx_resolve_virtual_array` vs `_hx_reslove_virtual_array`

**Comment by Simn** [comment]
Can we just transfer that typo to hxcpp?

**Comment by underscorediscovery** [comment]
If you mean have it spelt wrong on hxcpp side it already is.

**Comment by Simn** [comment]
Oh, so it's the same typo in both places? In that case I don't see why the typo matters.

**Comment by hughsando** [comment]
This is using the special command 'reslove', short for "resolution love".  Not really, but it will have to wait for a haxe update to fix.
I need to officially release 3.4.48 from http://nmehost.com/hxcpp/

**Comment by francoisvn** [comment]
This seems to be resolved (aka resloved) with hxcpp 3.4.49. Thanks
