### ISSUE TITLE
[lua] "Unfinished string" error after updating to 4.1.2

### ISSUE THREAD

**Issue by haath** [HaxeFoundation/haxe#9655]
Hello,

After updating Haxe to `4.1.2` I started getting the following issue.
The `NativeStackTrace` class generates this:

```lua
__haxe_NativeStackTrace.new = {}
__haxe_NativeStackTrace.__name__ = true
__haxe_NativeStackTrace.saveStack = function(exception) 
end
__haxe_NativeStackTrace.callStack = function() 
  local _g = debug.traceback();
  if (_g == nil) then 
    do return _hx_tab_array({}, 0) end;
  else
    local s = _g;
    local idx = 1;
    local ret = _hx_tab_array({}, 0);
    while (idx ~= nil) do 
      local newidx = 0;
      if (#"
" > 0) then 
        newidx = _G.string.find(s, "
", idx, true);
      else
        if (idx >= #s) then 
          newidx = nil;
        else
          newidx = idx + 1;
        end;
      end;
      if (newidx ~= nil) then 
        local match = _G.string.sub(s, idx, newidx - 1);
        ret:push(match);
        idx = newidx + #"
";
      else
        ret:push(_G.string.sub(s, idx, #s));
        idx = nil;
      end;
    end;
    do return ret:slice(3) end;
  end;
end
__haxe_NativeStackTrace.exceptionStack = function() 
  do return _hx_tab_array({}, 0) end;
end
```

Which then raises the following error when I try to run the lua code:

```
Line 3046: Compilation failed: unfinished string near '"'
```

The line in question is this one:

```haxe
        newidx = _G.string.find(s, "
", idx, true);
```

---

For reference:

- The lua code is being used with the [Defold](https://defold.com/) game engine.
- Windows 10.
- The exact same code with Haxe `4.0.5` does not have the `NativeStackTrace` module at all in the lua output.

**Comment by RealyUniqueName** [comment]
Huh. I can't reproduce it. I get proper `"\n"` strings in the output. And the generated code is different (e.g. there's no `_G` references in `callStack`)
Are you sure you're using Haxe 4.1 compiler? Could it be the older compiler with 4.1 std library?

**Comment by haath** [comment]
It looks like it...

![image](https://user-images.githubusercontent.com/29335643/86055312-d9f93680-ba5b-11ea-8ecb-ab53cc8a5937.png)

Is there something else I could check?

**Comment by haath** [comment]
Ok nevermind I figured out what was the problem. In my `hxml` I also call a patch script with `-cmd` which edits the lua file with `sed` and `echo`.

If I don't call the script the output has `"\n"` as you said.

So it's an issue with my unix skills and not Haxe, sorry for your time!
