### ISSUE TITLE
Java regression related to monomorphs as constructor arguments

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#3343]
```
class Main {
    static function main() {
        new Main(null);
    }

    function new(_) { }
}
```

```
src\haxe\root\Main.java:19: error: constructor Main(EmptyObject) is already defined in class Main
    public    Main(haxe.lang.EmptyObject _)
              ^
src\haxe\root\Main.java:47: error: constructor Main in class Main cannot be applied to given types;
        return new haxe.root.Main(arr.__get(0));
               ^
  required: EmptyObject
  found: Object
  reason: actual argument Object cannot be converted to EmptyObject by method invocation conversion
2 errors
Compilation error
Native compilation failed
```

This was broken by #3341, but I cannot for the life of me figure out the reason. I verified that the AST is identical, so it must be related to something else gencommon was relying on. I tried investigating that but couldn't find anything.

Help me obi-waneck. :(
