### ISSUE TITLE
[cpp] Missing field error with interface inheritance

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#4343]
This is as far as I could reduce it:

```haxe
class Main {
    static function main() {
		(new Test() : ITest).call();
    }
}

class Test implements ITest {
	public function new() {}
	public function call():Void {}
}

interface ITest extends IEmtpyExtendsCallable extends IEmpty {}

interface IEmpty {}

interface IEmtpyExtendsCallable extends ICallable {}

interface ICallable {
	public function call():Void;
}
```

```
./src/Main.cpp(46) : error C2039: 'call': Ist kein Element von 'ITest_obj'
        include\ITest.h(20): Siehe Deklaration von 'ITest_obj'

Error: Build failed
```

`call()` seems to be missing from `ITest.h`. This is a regression caused by 1fcc7c9.

**Comment by Simn** [comment]
@hughsando: Note that it works if the inheritance order is changed to `extends IEmpty extends IEmtpyExtendsCallable`. This looks like only the rightmost interface is taken into account somewhere.

**Comment by hughsando** [comment]
Yep, the code needs to be reasoned about carefully since I do not support multiple inheritance at the c++ level, so only one is interface actually extended, while the other must use delegation;

If you are after a work-around, doing this manually:
```((new Test() : ITest):ICallable).call();```
will be what I will need to do automatically in gencpp.

**Comment by ubald** [comment]
+1 here, using multiple interface inheritance on a huge project because it has always worked, this is a breaking change for me and probably many others.

**Comment by MSGhero** [comment]
@ubald lol I haven't been able to compile my game to native in 4 months, hope it still works there

**Comment by ubald** [comment]
@MSGhero I reverted to haxe 3.2.0 in the meantime
@hughsando Thanks
