### ISSUE TITLE
@:nativeGen half working on cpp

### ISSUE THREAD

**Issue by dmitryhryppa** [HaxeFoundation/haxe#7199]
Hello!
I didn't know that nativeGen available for cpp target, but Hugh pointed me to it. 
Also, Hugh told that he implemented it only for interfaces, but unfortunately it is not working in most cases :)

Here is small example:
```
package;
class App {
    public static function main():Void {
        var s:Something = new Something();
        s.test();

        //if comment this two lines, then "hello hxcpp" will be printed.
        //if uncomment then nothing be printed at all. 
        test1(s); //not working 
        test2(s); //not working
    }

    private static function test1(s:Something):Void {
        s.test();
    }

    private static function test2(s:ISomething):Void {
        s.test();
    }
}

class Something implements ISomething {
    public function new() {
        
    }

    public function test():Void {
        cpp.Lib.println("hello hxcpp!");
    }
}

@:nativeGen
interface ISomething {
    public function test():Void;
}
```

Also got compilation errors if @:nativeGen is applied on classes (but looks like it is expected, currently). 

But applying it on classes and interfaces generates very clean cpp code, which is so useful in some cases.
So I'm very excited about this feature and I hope it can be fixed and implemented in the same way as for Java and C# targets. 

Just look at this beautiful code (on left side with @:nativeGen, on right without) :)
![Image](https://image.ibb.co/gCedVJ/image.png)

**Comment by Simn** [comment]
What are the plans for `@:nativeGen` on hxcpp?

**Comment by hughsando** [comment]
The nativeGen should be working pretty much as designed now.

The code on the left does not support garbage collection, reflection, super functions or closures, which is what the extra code is about.  I don't think a haxe implementation can worth without these things.

**Comment by Simn** [comment]
Nice, thanks for the info!

**Comment by posxposy** [comment]
Well, it is not working in the same way as `@:nativeGen` for Java or C# targets. 
And it's even will not be compiled in many situations. 
So, maybe it should be renamed? Because when you target Java with nativeGen and then trying to compile it to C++, then compilation almost always will be broken. So you need to wrap all your nativeGen's to `#if java #end` statement. It is annoying. 
So, maybe rename it to cppNativeGen? While it is pretty specific for cpp. 

There is also a relative issue: https://github.com/HaxeFoundation/hxcpp/issues/721

**Comment by hughsando** [comment]
Maybe I need to disable it for classes, since it is really for interfaces at the moment.

**Comment by posxposy** [comment]
> Maybe I need to disable it for classes, since it is really for interfaces at the moment.
> The code on the left does not support garbage collection, reflection, super functions or closures, which is what the extra code is about. I don't think a haxe implementation can worth without these things.

I saw in tests, that nativeGen used on classes. That's why I'm trying to get it working.
So, I'm a bit confused :)
https://github.com/HaxeFoundation/hxcpp/blob/master/test/native/NativeGen.hx#L2

**Comment by posxposy** [comment]
Just tried it on interfaces and it won't compile with latest hxcpp (4.0.8) and haxe-rc-1
Example: 
```haxe
package;

class Index {
	public static function main():Void {
		final calc:SimpleCalculator = new SimpleCalculator();
		trace(calc.add(10, 20));
	}
}

class SimpleCalculator implements ICalculator {
	public function new() {
	}

	public function add(a:Int, b:Int):Int {
		return a + b;
	}
}

@:nativeGen
interface ICalculator {
	public function add(a:Int, b:Int):Int;
}
```

Compilation error:
```
Error: ./src/Index.cpp:35:67: error: call to non-static member function without an object argument
HXLINE(   5)             ::SimpleCalculator calc =  ::SimpleCalculator_obj::__new();
                                                    ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
```

I found that with natigeGen meta It is using `::__new();` to construct object instead of `::allog(ctx);'. Don't know it is by design or it is a bug.

**Comment by posxposy** [comment]
I know you guys very busy, so I'm ready to donate $50 to get `@:nativeGen` fix (for interfaces, as you said) :)
By PayPal if possible. Or by any crypto coin.
And would be nice to disable it on classes (to avoid compilation errors if you also targeting Java or C#).

I hope someone will join for these donations too.
