### ISSUE TITLE
[cpp] "Dynamic" as enum value 

### ISSUE THREAD

**Issue by pperidont** [HaxeFoundation/haxe#5084]
Using current git version of Haxe and hxcpp :
```
enum E {
	Dynamic;
}

class Main {
    public static function main(){}
}
```

```
Error: ./src/E.cpp:10:49: error: ‘Dynamic’ is not a type
 bool E_obj::__GetStatic(const ::String &inName, Dynamic &outValue, hx::PropertyAccess inCallProp)
```

That works on haxe 3.2.1 + hxcpp 3.2.205 (but fails with an other error on haxe 3.2.1 + hxcpp 3.2.102...)
