### ISSUE TITLE
[cpp] "no matching overloaded function" with nested Vectors

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5957]
This compiles in Haxe 3.2.1, making it another regression.

```haxe
import haxe.ds.Vector;

class Main {
	static var foo:Vector<Vector<Int>> = new Vector<Vector<Int>>(10);

	public static function main() {
		foo[0][0] += 1;
	}
}
```

```
./src/Main.cpp(34): error C2374: 'this11': redefinition; multiple initialization
./src/Main.cpp(32): note: see declaration of 'this11'
./src/Main.cpp(35): error C2672: '_hx_array_unsafe_get': no matching overloaded function found
Error: Build failed
```

Interestingly, the error goes away when turning `foo` into a local var.
Tested with Haxe 3.4.0-rc.2 + latest hxcpp dev.

**Comment by Simn** [comment]
Goddammit gama...

**Comment by Simn** [comment]
@hughsando: This is the last open 3.4 issue labeled as a regression. Anything to be done here?

**Comment by hughsando** [comment]
Looks like a problem with the inline-er, since the '-D dump' declares the this11 variable twice.
Python has a similar construct, but I assume no such error. 

I think it comes from "+=" where this11 is used in both the left and right hand sides.
The difference between c++ and python might be that cpp used "this.get" member notation, while python uses "get(this,..)" static notation.

**Comment by Simn** [comment]
Ah, I kind of ignored the duplicate var because the issue title talks about the other error. I suppose that makes this my problem...

**Comment by Simn** [comment]
```
Inline:
	Args: 
		length<507> = 10
		_this<506> = haxe.ds._Vector.Vector_Impl_
	Expr: {
		var this<422>;
		this<422> = cpp.NativeArray.create(length<421>);
		return cast this<422>;
	}
	Result: {
		var this<508>;
		this<508> = cpp.NativeArray.create(10);
		cast this<508>;
	}
Inline:
	Args: 
		index<512> = 0
		this<511> = Main.foo
		_this<510> = haxe.ds._Vector.Vector_Impl_
	Expr: {
		return cpp.NativeArray.unsafeGet(this<423>, index<424>);
	}
	Result: {
		var this<511> = Main.foo;
		cpp.NativeArray.unsafeGet(cast this<511>, 0);
	}
Inline:
	Args: 
		index<516> = 0
		this<515> = {
			var this<511> = Main.foo;
			cpp.NativeArray.unsafeGet(cast this<511>, 0);
		}
		_this<514> = haxe.ds._Vector.Vector_Impl_
	Expr: {
		return cpp.NativeArray.unsafeGet(this<423>, index<424>);
	}
	Result: {
		var this<515> = {
			var this<511> = Main.foo;
			cpp.NativeArray.unsafeGet(cast this<511>, 0);
		};
		cpp.NativeArray.unsafeGet(cast this<515>, 0);
	}
Inline:
	Args: 
		val<521> = {
			var this<515> = {
				var this<511> = Main.foo;
				cpp.NativeArray.unsafeGet(cast this<511>, 0);
			};
			cpp.NativeArray.unsafeGet(cast this<515>, 0);
		} + 1
		index<520> = 0
		this<519> = {
			var this<511> = Main.foo;
			cpp.NativeArray.unsafeGet(cast this<511>, 0);
		}
		_this<518> = haxe.ds._Vector.Vector_Impl_
	Expr: {
		return cast this<425>.__unsafe_set(index<426>, val<427>);
	}
	Result: {
		var this<519> = {
			var this<511> = Main.foo;
			cpp.NativeArray.unsafeGet(cast this<511>, 0);
		};
		var val<521> = {
			var this<515> = {
				var this<511> = Main.foo;
				cpp.NativeArray.unsafeGet(cast this<511>, 0);
			};
			cpp.NativeArray.unsafeGet(cast this<515>, 0);
		} + 1;
		cast cast this<519>.__unsafe_set(0, val<521>);
	}
```

So the problem seems to be that two different calls pull the same abstract `this` variable (511) into the scope.
