### ISSUE TITLE
C2065 and C2039 with @:rtti on interfaces

### ISSUE THREAD

**Issue by Jens-G** [HaxeFoundation/haxe#3626]
The following code works with JavaScript http://try.haxe.org/#30d50.
It does not work with Haxe 3.1.3 and a CPP target.

    @:rtti
    interface Wtf {
        function doit() : Void;
    }

    @:rtti
    class Main implements Wtf {
        static function main() {
            var inst : Wtf = new Main();
            inst.doit();
        }
        
        public function new() { }
        
        public function doit() : Void {
            trace('I did it');
        }
    }

Running `haxe  -cp src -cpp bin -main Main` gives me 

    Wtf.cpp
    ./src/Wtf.cpp(16) : error C2039: '__rtti': Ist kein Element von 'Wtf_obj'
            include\Wtf.h(11): Siehe Deklaration von 'Wtf_obj'
    ./src/Wtf.cpp(16) : error C2065: '__rtti': nichtdeklarierter Bezeichner
    ./src/Wtf.cpp(22) : error C2039: '__rtti': Ist kein Element von 'Wtf_obj'
            include\Wtf.h(11): Siehe Deklaration von 'Wtf_obj'
    ./src/Wtf.cpp(22) : error C2065: '__rtti': nichtdeklarierter Bezeichner
    ./src/Wtf.cpp(45) : error C2065: '__rtti': nichtdeklarierter Bezeichner
