### ISSUE TITLE
haxe 3.4.5 gives lots of macros about spods but record-macros lib is not compatible

### ISSUE THREAD

**Issue by sebpatu** [HaxeFoundation/haxe#6834]
Hello,
when we compile with haxe 3.4.5 lots of warnings recommend to use record-macros lib.
but if we get the latests release with haxelib install the code does not compile.
only for a very obscure reason:
the code of this release is exactly the same than in haxe 3.4.5 std library except for two lines that are the reason of the compilation error:
HaxeToolkit\3.4.5\lib\record-macros/1,0,0-alpha/src/sys/db/RecordMacros.hx:785: characters 8-12 : Capture variables must be lower-case

the case OpIn: line but OpIn does not exist in haxe 3.4.5

to make the haxe 3.4.5 adoption easier, could you please release a lib version that is working fine with haxe 3.4.5 please? a perfect copy of the standard lib code without warnings, at least, or the latests code version, if its passing all tests.

thanks
i added this issue to the library guithub too, but its also responsibliity of the haxe compiler because it recommend to use it with lots of warnings, making the haxe update not as smooth as it should be

**Comment by RealyUniqueName** [comment]
Are you sure you're using record-macros installed from haxelib without modifications?
It doesn't even have any `OpIn` in whole source code.

**Comment by sebpatu** [comment]
sorry i reinstalled the lib and you'r right its not in it.
i presumably added it when i tried to compile in haxe 4.
sorry again
