### ISSUE TITLE
[cs] Conditional operator fails to compile with error CS0173

### ISSUE THREAD

**Issue by vroad** [HaxeFoundation/haxe#5466]
I tried to do some tests with `Std.is`, but the code I pasted below doesn't compile.

```hx
package;

class Base
{
	private function new()
	{
	}
}

class A extends Base
{
	public function new()
	{
		super();
	}
}

class B extends Base
{
	public function new()
	{
		super();
	}
}

class Main 
{
	static function main() 
	{
		var count:Int = 0;
		for (i in 0 ... 10000)
		{
			var flag:Bool = Math.round(Math.random()) == 1;
			var test:Base = flag ? new A () : new B ();
			
			if (Std.is(test, A))
				count++;
		}
		trace(count);
	}
}
```

```cs
public static void main() {
		unchecked {
			int count = 0;
			{
				int _g = 0;
				while (( _g < 10000 )) {
					 ++ _g;
					if (( ( (( global::Math.round(global::Math.rand.NextDouble()) == 1 )) ? (new global::A()) : (new global::B()) ) is global::A )) {
						 ++ count;
					}
					
				}
				
			}
			
			global::haxe.Log.trace.__hx_invoke2_o(((double) (count) ), global::haxe.lang.Runtime.undefined, default(double), new global::haxe.lang.DynamicObject(new int[]{302979532, 1547539107, 1648581351}, new object[]{"main", "Main", "Main.hx"}, new int[]{1981972957}, new double[]{((double) (39) )}));
		}
	}
```

This code compiles on Haxe 3.2 without errors. I guess it compiles on 3.2 because it doesn't automatically remove local variables.
Can I turn off automatic removal of local variables and inlining on Haxe3.3? I think it just makes generated source code harder to read on cs.

https://msdn.microsoft.com/en-us/library/hb47kt2f.aspx

**Comment by vroad** [comment]
I didn't understand the error. Disabling static analyzer didn't solve the problem. It didn't compile because C# compiler doesn't cast `B` and `A` to its base class(`Base`) implicitly when conditional operator is used.
Errors will go away by adding cast manually like this.

```cs
global::Base test = ( (flag) ? ((Base)new global::A()) : ((Base)new global::B()) );
```

**Comment by nadako** [comment]
A somewhat reduced example:
```haxe
class Base {
    public function new() {}
}

class A extends Base {}

class B extends Base {}

class Main {
    static function main() {
        var test:Base = if (Math.random() > 0.5) new A() else new B();
        Sys.println(test);
    }
}
```

generates:
```cs
global::System.Console.WriteLine(((object) (( (( global::Math.rand.NextDouble() > 0.5 )) ? (new global::A()) : (new global::B()) )) ));
```

and the `CS0173` error as originally mentioned.

This is a regression. The symptom is probably caused by the analyzer changes,but the actual cause is the missing cast in gencommon/gencs. @waneck please!

**Comment by nadako** [comment]
@Simn the ast for this looks correct:
```
				[If:Base]
					[Parenthesis:Bool]
						[Binop:Bool]
							[Call:Float]
								[Field:Void -> Float]
									[Field:System.Random]
										[TypeExpr Math:Class<Math>]
										[FStatic:System.Random]
											Math
											rand
									[FInstance:Void -> Float]
										System.Random
										NextDouble
							>
							[Const:Float] 0.5
					[Then:A] [New:A] A
					[Else:B] [New:B] B

```
however wouldn't it make sense to type then/else expressions as `Base` here, for all targets?

**Comment by nadako** [comment]
or maybe add a cast, or something...

**Comment by Simn** [comment]
We usually don't insert TCast for upcasts... I don't really mind but I also don't really trust TCast in general.

**Comment by vroad** [comment]
MSDN page says you can solve this by adding implicit cast operator to the class. Does that help?

I said using static analyzer makes source code harder to read, but I've just learned that using local variables is bad for JIT performance. Then it sounds like a good idea to enable static analyzer for C# as it reduces the number of local variables, at least for performance.

**Comment by nadako** [comment]
Static analyzer is enabled for all targets now, and yes, performance is a priority here. The code readability is okay-ish and one could use some c# formatting tool to read it easier.

OTOH as you mentioned in #5465, analyzer does a couple things differently on static targets which can cause performance differences. However I was pretty sure that mono compiler does some optimizations itself and pack the local vars back. We'll need to research on that.

**Comment by vroad** [comment]
I used Visual Studio 2015's compiler for compiling. Benchmark results suggests that Visual Studio's compiler does not optimize local variables away. I've also tried compiling without debug information and that didn't seem to make difference.

http://stackoverflow.com/questions/7664046/allowed-c-sharp-compiler-optimization-on-local-variables-and-refetching-value-fr

Is the removal of local variables at compile time really allowed?

Whether it's allowed or not, Visual Studio's compiler does not remove local variables in practice, I suppose. CoreCLR may remove that at JIT compilation, though.

**Comment by vroad** [comment]
Also, using local variables may prevent JIT compiler from inlining functions.
http://stackoverflow.com/questions/26369163/net-local-variable-optimization

**Comment by dimmp** [comment]
I was writing some unit tests when I managed to prompt a CS0173 error.

Assuming that we declare two local variables:
```
var condition = true;
var someValue:Int;
```
The following code fails at c# compile time:
```
var f = if (condition) 
            function () { someValue = 0; }
        else 
            function () { someValue = 0; };
```
The generated code:
```
global::haxe.lang.Function f = ( (condition) ? (new global::tests.MyClass_myFunc_91__Fun(someValue)) : (new global::tests.MyClass_myFunc_93__Fun(someValue)) );
```

It seems like the c# compiler needs an explicit conversion of `MyClass_myFunc_91__Fun` and/or `MyClass_myFunc_93__Fun` to `haxe.lang.Function`. 

If the functions doesn't use any fields or variables coming from outside the function body, such as `someValue`, the generated code do the explicite conversion:
```
Function f = condition ? (Function)new MyClass_myFunc_91__Fun() : new MyClass_myFunc_93__Fun(someValue);
```
