### ISSUE TITLE
[cs] Type constraints causing invalid C# code

### ISSUE THREAD

**Issue by dogles** [HaxeFoundation/haxe#4002]
Tested with latest Haxe on git.
Repro: Compile the following code to C#:

```
package;

class A {
  public function foo() {}
}

class B<T:A> {
  public var a:T;
  public function new(a:T) {
    this.a = a;
    var x = function() {
      a.foo();
    }
    x();
  }
}

class BugTest {
  public static function main() {}
}
```

Result: Error in C# compilation:
BugTest.hx(11,38): error CS0314: The type `T_c' cannot be used as type parameter `T_c' in the generic type or method `B___hx_ctor__B_11__Fun<T_c>'. There is no boxing or type parameter conversion from `T_c' to `A'

The problem is that the C# type parameter constraint is specified for the functor, but not on the class or static hx_ctor method. This is a recent regression.

**Comment by nadako** [comment]
Hmm, this is probably caused by f045215fbf65b51504cecb30f5713787d9deb0a3, I had no idea that closure classes are `@:nativeGen` as well.

**Comment by waneck** [comment]
Yeah, they are so they avoid having all that reflection classes, @nadako . The fix seems easy enough though
