### ISSUE TITLE
Typedef multiple inheritance

### ISSUE THREAD

**Issue by RblSb** [HaxeFoundation/haxe#6565]
Compilation error without comma at the end
https://try.haxe.org/#12eF7

**Comment by nadako** [comment]
I would also like it to support `;` for the class notation, e.g.

```haxe
typedef Some = {
    >Base;
    var field:Int;
}
```

**Comment by Simn** [comment]
If we want to allow the class notation, I think we should disallow the `,` usage there. In other words, `;` should lock you in class notation whereas `,` locks you in structure notation.

That's a breaking change, but I really don't want to allow mixing `;` and `,` in this syntax...

**Comment by Simn** [comment]
We decided to leave this syntax alone and instead focus on the `Type1 & Type2` syntax introduced in #7127.
